plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.misfit1000.streamnyaa'
version = '0.1.0'

expoModule {
  canBePublished false
}

android {
  namespace 'com.misfit1000.streamnyaa.torrent'
  defaultConfig {
    minSdk 24
    versionCode 1
    versionName '0.1.0'
    consumerProguardFiles 'consumer-rules.pro'
  }
}

dependencies {
  implementation 'org.libtorrent4j:libtorrent4j:2.1.0-35'
  runtimeOnly 'org.libtorrent4j:libtorrent4j-android-arm:2.1.0-35'
  runtimeOnly 'org.libtorrent4j:libtorrent4j-android-arm64:2.1.0-35'
  runtimeOnly 'org.libtorrent4j:libtorrent4j-android-x86:2.1.0-35'
  runtimeOnly 'org.libtorrent4j:libtorrent4j-android-x86_64:2.1.0-35'
  implementation 'org.nanohttpd:nanohttpd:2.3.1'
}
