$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$repo = Split-Path -Parent $root

function Assert-Match {
  param(
    [string]$Value,
    [string]$Pattern,
    [string]$Message
  )

  if ($Value -notmatch $Pattern) {
    throw $Message
  }
}

function Assert-NotMatch {
  param(
    [string]$Value,
    [string]$Pattern,
    [string]$Message
  )

  if ($Value -match $Pattern) {
    throw $Message
  }
}

$desktopBridge = Get-Content -Raw (Join-Path $repo 'src\lib\desktop.ts')
$watchPage = Get-Content -Raw (Join-Path $repo 'src\pages\DesktopWatch.tsx')
$appDesktop = Get-Content -Raw (Join-Path $repo 'src\AppDesktop.tsx')
$desktopShell = Get-Content -Raw (Join-Path $repo 'src\components\DesktopShell.tsx')
$mainDesktop = Get-Content -Raw (Join-Path $repo 'src\main.desktop.tsx')
$animeCard = Get-Content -Raw (Join-Path $repo 'src\components\AnimeCard.tsx')
$jikanApi = Get-Content -Raw (Join-Path $repo 'src\api\jikan.ts')
$desktopHome = Get-Content -Raw (Join-Path $repo 'src\pages\DesktopHome.tsx')
$desktopExplore = Get-Content -Raw (Join-Path $repo 'src\pages\DesktopExplore.tsx')
$desktopLibrary = Get-Content -Raw (Join-Path $repo 'src\pages\DesktopLibrary.tsx')
$desktopSources = Get-Content -Raw (Join-Path $repo 'src\pages\DesktopSources.tsx')
$desktopSettings = Get-Content -Raw (Join-Path $repo 'src\pages\DesktopSettings.tsx')
$desktopSchedule = Get-Content -Raw (Join-Path $repo 'src\pages\DesktopSchedule.tsx')
$desktopHistory = Get-Content -Raw (Join-Path $repo 'src\pages\DesktopHistory.tsx')
$desktopReminders = Get-Content -Raw (Join-Path $repo 'src\lib\desktopReminders.ts')
$desktopRoutePreload = Get-Content -Raw (Join-Path $repo 'src\lib\desktopRoutePreload.ts')
$desktopQuerySnapshot = Get-Content -Raw (Join-Path $repo 'src\lib\desktopQuerySnapshot.ts')
$desktopShell = Get-Content -Raw (Join-Path $repo 'src\components\DesktopShell.tsx')
$desktopNotificationCenter = Get-Content -Raw (Join-Path $repo 'src\components\DesktopNotificationCenter.tsx')
$desktopScheduleRevisions = Get-Content -Raw (Join-Path $repo 'src\lib\scheduleRevisions.ts')
$desktopExploreCache = Get-Content -Raw (Join-Path $repo 'src\lib\desktopExploreCache.ts')
$desktopScheduleCache = Get-Content -Raw (Join-Path $repo 'src\lib\desktopScheduleCache.ts')
$desktopCatalogCache = Get-Content -Raw (Join-Path $repo 'src\lib\desktopCatalogCache.ts')
$desktopSecurity = Get-Content -Raw (Join-Path $repo 'src\lib\desktopSecurity.ts')
$desktopQueryClient = Get-Content -Raw (Join-Path $repo 'src\lib\queryClient.ts')
$desktopPlayerShortcuts = Get-Content -Raw (Join-Path $repo 'src\lib\desktopPlayerShortcuts.ts')
$upcomingNotifyButton = Get-Content -Raw (Join-Path $repo 'src\components\UpcomingNotifyButton.tsx')
$desktopCss = Get-Content -Raw (Join-Path $repo 'src\index.css')
$desktopArtwork = Get-Content -Raw (Join-Path $repo 'src\lib\desktopArtwork.ts')
$loginPage = Get-Content -Raw (Join-Path $repo 'src\pages\Login.tsx')
$supabaseAuth = Get-Content -Raw (Join-Path $repo 'src\lib\supabaseAuth.ts')
$nyaaApi = Get-Content -Raw (Join-Path $repo 'src\api\nyaa.ts')
$metadataApi = Get-Content -Raw (Join-Path $repo 'src\api\jikan.ts')
$streamSourcesApi = Get-Content -Raw (Join-Path $repo 'api\stream-sources.ts')
$tauriMain = Get-Content -Raw (Join-Path $repo 'desktop\src-tauri\src\main.rs')
$workflow = Get-Content -Raw (Join-Path $repo '.github\workflows\desktop-release.yml')
$packageJson = Get-Content -Raw (Join-Path $repo 'package.json')
$desktopHtmlWriter = Get-Content -Raw (Join-Path $repo 'scripts\write-desktop-html.mjs')
$desktopFallbackBuilder = Get-Content -Raw (Join-Path $repo 'scripts\build-desktop-fallback.ps1')
$playerSkin = Get-Content -Raw (Join-Path $repo 'desktop\src-tauri\bin\streamnyaa-player.lua')
$tauriConfig = Get-Content -Raw (Join-Path $repo 'desktop\src-tauri\tauri.conf.json')
$tauriCapability = Get-Content -Raw (Join-Path $repo 'desktop\src-tauri\capabilities\main.json')
$cargoManifest = Get-Content -Raw (Join-Path $repo 'desktop\src-tauri\Cargo.toml')
$releasePreparer = Get-Content -Raw (Join-Path $repo 'scripts\prepare-desktop-release.ps1')

Assert-Match $desktopBridge "DEFAULT_DESKTOP_SETTINGS:\s*DesktopPlaybackSettings\s*=\s*\{\s*torrent_engine_path:\s*''" 'Desktop settings should default to bundled engine lookup.'
Assert-Match $tauriConfig '"version"\s*:\s*"0\.1\.7"' 'Desktop release configuration should target version 0.1.7.'
Assert-Match $cargoManifest 'version\s*=\s*"0\.1\.7"' 'Rust package version should match the desktop release version.'
Assert-Match $releasePreparer "releaseRevision\s*=\s*'desktop-loading-recovery-9'" 'The 0.1.7 release manifest must identify the current loading, recovery, artwork handoff, player controls, and request-hardening pass.'
Assert-Match $releasePreparer 'auth-recovery-live-validation\.json' 'The 0.1.3 artifact must remain gated on live password-recovery validation.'
Assert-Match $releasePreparer '2MB' 'The installer must reject growth beyond the two MiB budget.'
Assert-Match $desktopBridge '__STREAMNYAA_DESKTOP__' 'Desktop detection should use the explicit desktop runtime flag.'
if ($desktopBridge -match 'VITE_STREAMNYAA_APP_TARGET') {
  throw 'Desktop runtime detection must not depend on build-time env replacement.'
}
Assert-Match $mainDesktop 'window\.__STREAMNYAA_DESKTOP__\s*=\s*true' 'Desktop entry must set the explicit desktop runtime flag.'
Assert-Match $desktopBridge 'buildDesktopDiagnosticsReport' 'Desktop diagnostics report helper is missing.'
Assert-Match $desktopBridge 'loadDesktopAudioPreference' 'Desktop audio preference loader is missing.'
Assert-Match $desktopBridge 'loadDesktopAutoOpenBestSource' 'Desktop auto-open source preference loader is missing.'
Assert-Match $desktopBridge 'latestUnwatchedEpisodeForAnime' 'Desktop latest-unwatched helper is missing.'
Assert-Match $desktopBridge 'streamnyaa\.desktop\.watchProgress\.v1' 'Desktop watch progress storage key is missing.'
Assert-Match $desktopBridge 'DesktopWatchProgressRecord' 'Desktop watch progress record type is missing.'
Assert-Match $desktopBridge 'resolveDesktopPlaybackCheckpoint' 'Desktop playback should resolve one canonical checkpoint across sources.'
Assert-Match $desktopBridge 'existing\.updatedAt.*>.*normalized\.updatedAt' 'Older account checkpoints must not replace a newer deliberate seek.'
Assert-Match $desktopBridge 'Torrent completion and watched completion are independent metrics' 'Torrent completion must not be stored as episode watch completion.'
Assert-Match $desktopBridge 'setDesktopEpisodeWatched' 'Desktop watch progress should support explicit watched and unwatched actions.'
Assert-Match $desktopBridge 'exportDesktopSettingsBackup' 'Desktop settings export helper is missing.'
Assert-Match $desktopBridge 'importDesktopSettingsBackup' 'Desktop settings import helper is missing.'
Assert-Match $appDesktop 'path="watch/:id"' 'Desktop route tree should own the watch route.'
Assert-Match $appDesktop 'path="anime/:id"\s+element=\{<AnimeToDesktopWatch\s*/>\}' 'Desktop anime routes must redirect to the desktop watch page.'
Assert-Match $desktopShell 'SIDEBAR_STORAGE_KEY' 'Desktop shell should persist sidebar collapse state.'
Assert-Match $desktopShell 'setSidebarCollapsed' 'Desktop shell menu button should toggle the sidebar.'
Assert-Match $desktopShell 'warmCoreDesktopRoutes' 'Desktop shell should warm core route chunks after first paint.'
Assert-Match $desktopShell 'preloadDesktopRoute' 'Desktop navigation should preload routes on user intent.'
Assert-Match $desktopShell 'readDesktopScheduleReminders' 'Desktop reminder checks should sleep when no reminders are pending.'
Assert-NotMatch $desktopShell 'setInterval\(\(\) => void checkReminders' 'Desktop reminders must not poll forever when no reminders exist.'
Assert-Match $desktopHome 'secondaryRailsReady' 'Desktop home should defer non-critical rails until after first paint.'
Assert-Match $desktopHome 'requestIdleCallback' 'Desktop home should warm secondary rail data during idle time.'
Assert-NotMatch $desktopShell 'key=\{location\.pathname\}' 'Desktop routes must not force a full remount on every navigation.'
Assert-Match $desktopRoutePreload 'MAX_CONCURRENT_WARMS\s*=\s*2' 'Desktop route warming must stay limited to two concurrent imports.'
Assert-Match $desktopRoutePreload 'requestIdleCallback' 'Desktop route warming should wait for an idle browser window.'
Assert-Match $desktopRoutePreload 'playbackWorkloadBusy' 'Nonessential route warming should pause while playback is recovering.'
Assert-Match $desktopQuerySnapshot 'PUBLIC_QUERY_PREFIXES' 'Offline-first restoration must use an explicit public-data allowlist.'
Assert-NotMatch $desktopQuerySnapshot 'account-library' 'Private account queries must never be included in public screen snapshots.'
Assert-Match $watchPage 'preloadDesktopWatchData.*true' 'Watch should prepare the next episode source list before autoplay needs it.'
Assert-Match $appDesktop 'desktopPageLoaders' 'Desktop lazy routes should share the preload registry promises.'
Assert-Match $desktopShell 'ShortcutHelpOverlay' 'Desktop shell shortcut overlay is missing.'
Assert-Match $desktopShell 'isTypingTarget' 'Desktop shortcut overlay should ignore text entry targets.'
Assert-Match $desktopShell "event\.key === '\?'" 'Desktop shortcut overlay should open with the ? key.'
Assert-Match $desktopShell 'HOVER_PRELOAD_DELAY_MS\s*=\s*80' 'Desktop metadata preloading should begin quickly after deliberate hover intent.'
Assert-Match $desktopShell 'HOVER_SOURCE_PRELOAD_DELAY_MS\s*=\s*360' 'Desktop source preloading should require sustained Watch intent.'
Assert-Match $desktopShell 'preloadLinkedRouteNow\(event\.target, true\)' 'Pointer-down should bypass the hover delay and begin Watch source preloading immediately.'
Assert-Match $appDesktop "path=`"search`" element=\{<DesktopExplore />\}" 'Desktop Explore must use the desktop-native page.'
Assert-Match $appDesktop "path=`"nyaa`" element=\{<DesktopSources />\}" 'Desktop Sources must use the desktop-native page.'
Assert-Match $appDesktop "path=`"schedule`" element=\{<DesktopSchedule />\}" 'Desktop Schedule must use the desktop-native page.'
Assert-Match $appDesktop "path=`"profile`" element=\{<DesktopProfile />\}" 'Desktop Profile must use the desktop-native profile page.'
Assert-Match $appDesktop "path=`"login`" element=\{<Login />\}" 'Desktop Login route should stay inside AppDesktop and DesktopShell.'
if ($appDesktop -match "import\\('./pages/AnimeDetails'\\)") {
  throw 'Desktop app must not mount the web anime details page.'
}
Assert-Match $loginPage "isDesktopRuntime\(\) \? '/profile' : '/dashboard'" 'Desktop login should default successful auth to the native profile route.'
Assert-Match $supabaseAuth 'if \(isDesktopRuntime\(\)\)' 'Supabase auth redirects must branch for the desktop runtime before using hosted web origins.'
Assert-Match $supabaseAuth 'safeAuthRedirectPath' 'Auth redirects should sanitize callback paths before building redirect URLs.'
Assert-Match $supabaseAuth "DESKTOP_AUTH_CALLBACK_ORIGIN\s*=\s*'streamnyaa://auth/callback'" 'Desktop authentication must return through the registered native callback.'
Assert-Match $supabaseAuth "prompt'.*'select_account'|prompt.*,.*select_account" 'Desktop Google OAuth must request the account chooser.'
Assert-Match $supabaseAuth "nativeRecoveryRedirectUrl\('desktop'" 'Desktop password recovery must use the verified HTTPS-to-native relay.'
Assert-Match $supabaseAuth "desktopAuthRedirectUrl\('confirmation'" 'Desktop email confirmation must use its native callback action.'
Assert-Match $desktopBridge 'take_pending_desktop_oauth_callback' 'Desktop OAuth callbacks must survive a cold frontend start.'
Assert-Match $animeCard 'desktopWatchOrBrowsePath\(anime\)' 'Desktop anime cards must use the desktop-specific watch routing helper.'
Assert-Match $desktopHome 'desktopWatchPath\(anime' 'Desktop home should build watch links through the desktop-specific route helper.'
Assert-Match $desktopHome 'loadDesktopAudioPreference' 'Desktop home should respect the pinned audio preference.'
Assert-Match $desktopHome 'watchEpisodeFor' 'Desktop home should open the latest unwatched episode when possible.'
Assert-Match $watchPage 'Playback Options' 'Desktop watch page playback-options section is missing.'
Assert-Match $watchPage 'Play Episode' 'Desktop watch page primary play action is missing.'
Assert-NotMatch $watchPage 'Source Links' 'Desktop watch page must not render the old Source Links label.'
Assert-NotMatch $watchPage 'Smart Source Selector|Smart source selector' 'Desktop watch page must not render the old smart source selector label.'
Assert-NotMatch $watchPage 'Available Sources' 'Desktop watch page must not render the old Available Sources label.'
Assert-NotMatch $watchPage '>[\s\r\n]*Play Episode[\s\r\n]*<' 'Desktop watch page must not render the old Play Episode action.'
Assert-Match $watchPage 'saveDesktopAudioPreference' 'Desktop watch page should persist audio preference changes.'
Assert-Match $watchPage 'saveDesktopAutoOpenBestSource' 'Desktop watch page should persist episode click behavior changes.'
Assert-Match $watchPage 'sourceQualityReasons' 'Desktop watch page should explain why source matches are ranked.'
Assert-Match $watchPage 'fallbackAnimeFromRoute' 'Desktop watch page must fall back to a route title when metadata lookup fails.'
Assert-Match $watchPage 'SafeImage' 'Desktop watch page must render fallback-safe images.'
Assert-Match $watchPage 'episodeNumberFromTitle' 'Desktop watch page should avoid mismatching episode thumbnails and titles.'
Assert-Match $watchPage 'selectedEpisode - Math\.floor\(maxVisible / 2\)' 'Desktop watch page should keep the selected long-running episode in the visible strip.'
Assert-Match $watchPage 'sourceSearchTitleVariants' 'Desktop watch page should widen source title matching for alternate season naming.'
Assert-Match $watchPage 'sourceMatchesInstallment' 'Desktop watch page should filter torrent sources by the selected installment.'
Assert-Match $watchPage 'TIMELINE_RELATIONS' 'Desktop watch page should build a complete related-series timeline instead of only direct sequel pills.'
Assert-Match $watchPage "'SIDE_STORY'" 'Desktop watch page should allow OVA/special timeline entries while still filtering non-anime media.'
Assert-Match $watchPage 'Promise\.allSettled' 'Desktop watch page should expand related installments in batches so the timeline appears complete.'
Assert-Match $watchPage 'sameSeriesFamily' 'Desktop watch page should keep season traversal inside the same title family.'
Assert-Match $watchPage 'hasSeasonTitleSignal' 'Desktop watch page should avoid fake season labels for unlabeled TV relations.'
Assert-Match $watchPage 'sourceSeasonNumber' 'Desktop watch page should keep hidden season ordinals for torrent source matching without fake season labels.'
Assert-Match $watchPage 'installment\?\.sourceSeasonNumber' 'Desktop source search should use hidden season ordinals when visible labels stay title-based.'
Assert-Match $watchPage 'status === ''NOT_YET_RELEASED''' 'Desktop watch page should not include unreleased relation entries in aired installment rails.'
Assert-Match $watchPage 'isAncillarySource' 'Desktop watch page should reject OP/ED and other ancillary torrent files.'
Assert-Match $watchPage 'classifySource' 'Desktop watch page should classify sources before playback.'
Assert-Match $watchPage 'parseSourceAnimeTitle' 'Desktop watch page should parse torrent titles before comparing anime titles.'
Assert-Match $watchPage 'sourceTitleCompatibility' 'Desktop watch page should globally gate torrent sources by compatible anime titles.'
Assert-Match $watchPage 'rejected:single-token-overlap' 'Desktop watch page should reject one-token overlaps such as Vampire Hunter D for Hunter x Hunter.'
Assert-Match $watchPage 'rejected:title-mismatch' 'Desktop watch page should reject unrelated anime titles before source bucketing.'
Assert-Match $watchPage 'isSafeSourceQueryTitle' 'Desktop watch page should avoid unsafe one-word source queries from multi-word anime titles.'
Assert-Match $watchPage 'matchTier\s*=\s*''exact''' 'Desktop watch page should keep exact same-episode sources separate from loose matches.'
Assert-Match $watchPage "useState<SourceFilterMode>\('balanced'\)" 'Desktop watch page should default to Balanced sources so usable non-exact sources are visible.'
Assert-Match $watchPage 'Wide match' 'Desktop watch page should allow wider seeded source candidates instead of hiding every non-exact torrent.'
Assert-Match $watchPage 'FAILED_SOURCE_MEMORY_KEY' 'Desktop watch page should remember recently failed sources.'
Assert-Match $watchPage 'rememberSourceFailure' 'Desktop watch page should record failed source handoffs.'
Assert-Match $watchPage 'Try another stream' 'Desktop watch page should expose a same-episode recovery action.'
Assert-Match $watchPage "source\.matchTier === 'broad'" 'Desktop playback retry should allow broad backups when broad is the selected playable pool.'
Assert-Match $watchPage 'isFetching:\s*sourcesFetching' 'Desktop watch page should track source refetching during episode switches.'
Assert-Match $watchPage 'SOURCE_SEARCH_BUDGET_MS\s*=\s*12_000' 'Desktop source discovery must have a fast bounded total search budget.'
Assert-Match $watchPage 'SOURCE_RETRY_LIMIT\s*=\s*4' 'Desktop playback should try the selected source plus no more than three automatic backups.'
Assert-Match $watchPage 'publishPartial' 'Desktop source discovery should publish compatible results before broad fallback finishes.'
Assert-Match $watchPage '\{ \.\.\.options, signal \}' 'Desktop source discovery should consume React Query cancellation signals.'
Assert-Match $watchPage 'query-timeout' 'Desktop source discovery should report and recover from a slow provider query.'
Assert-Match $watchPage 'sourcesBusy\s*=\s*sourcesLoading\s*\|\|\s*sourcesFetching' 'Desktop autoplay should wait until the selected episode source query is fully settled.'
Assert-Match $watchPage 'playableSourcesEpisodeRef\.current\s*!==\s*selectedEpisode' 'Desktop autoplay should reject stale sources from the previous episode.'
Assert-Match $watchPage 'activeSourceId\s*\|\|\s*playActionLockRef\.current\) return' 'Desktop autoplay should wait for active player handoff before opening the next source.'
Assert-Match $watchPage 'EPISODE_RAIL_DRAG_THRESHOLD\s*=\s*12' 'Desktop episode rail should use a deliberate drag threshold that preserves clicks.'
Assert-Match $watchPage 'watchEpisodeFromCard' 'Desktop episode cards should use a click-to-watch helper instead of select-only behavior.'
Assert-Match $watchPage 'watchEpisodeFromCard\(episode\.number\)' 'Desktop episode cards should open playback for the clicked episode.'
Assert-Match $watchPage 'isIntentionalHorizontalDrag\(deltaX,\s*deltaY,\s*EPISODE_RAIL_DRAG_THRESHOLD\)' 'Desktop episode rail drag suppression should only start after intentional horizontal movement.'
Assert-Match $watchPage 'desktopWatchPath\(' 'Desktop watch page season switches should preserve the resolved desktop route identity.'
if ($watchPage -match 'Anime not found') {
  throw 'Desktop watch page must not dead-end on "Anime not found".'
}
if ($jikanApi -match '(?m)^\s*rank\s*$') {
  throw 'AniList queries must not request unsupported rank fields.'
}
Assert-Match $jikanApi 'animeDetailsCandidateScore' 'Desktop metadata resolution should score AniList detail candidates instead of trusting one fallback path.'
Assert-Match $jikanApi 'preferredAniListId' 'Desktop metadata resolution should preserve explicit AniList ids through watch-page routes.'
Assert-Match $jikanApi 'startDate \{ year month day \}' 'AniList relation metadata should include start dates for chronological installment sorting.'
Assert-Match $jikanApi 'status: edge\.node\.status' 'AniList relation metadata should include release status for aired installment filtering.'
if ($desktopHome -match 'bx145064-YspYpO4wXHNP') {
  throw 'Desktop fallback data still contains the broken Jujutsu Kaisen image URL.'
}
if ($desktopHome -match 'return live\.length \? live : FALLBACK_DESKTOP_ANIME') {
  throw 'Desktop home must not fill live rows with repeated fallback anime.'
}
Assert-Match $desktopHome 'fetchAnimeSeason' 'Desktop home should load the current anime season instead of repeating generic airing data.'
Assert-Match $desktopHome 'searchAnime\(' 'Desktop home should use a dedicated trending feed instead of reusing seasonal rows.'
Assert-Match $desktopHome 'Details' 'Desktop Continue Watching cards should expose a details action.'
Assert-Match $desktopHome 'sourceUpdatedLabel' 'Desktop Continue Watching cards should show last watched context.'
Assert-Match $desktopExplore 'fetchAnimeSeason' 'Desktop Explore should load the current anime season.'
Assert-Match $desktopLibrary 'Watching' 'Desktop Library should expose a Watching category.'
Assert-Match $desktopLibrary 'Completed' 'Desktop Library should expose a Completed category.'
Assert-Match $desktopLibrary 'Plan to Watch' 'Desktop Library should expose a Plan to Watch category.'
Assert-Match $desktopLibrary 'Favorites' 'Desktop Library should expose a Favorites category.'
Assert-Match $desktopLibrary 'History' 'Desktop Library should expose a History category.'
Assert-Match $desktopSources 'Batch sources hidden' 'Desktop Sources should hide batch files.'
Assert-Match $desktopSources 'loadDesktopAudioPreference' 'Desktop Sources should start from the pinned audio preference.'
Assert-Match $desktopSettings 'Autoplay episodes' 'Desktop Settings should expose the episode click behavior preference.'
Assert-Match $desktopSettings 'Personal alerts' 'Desktop Settings should expose personal delay and cancellation alerts.'
Assert-Match $desktopSettings 'Global alerts' 'Desktop Settings should expose global delay and cancellation alerts.'
Assert-Match $desktopSettings 'Settings sections' 'Desktop Settings should provide direct category navigation.'
Assert-Match $desktopSettings 'Keyboard controls' 'Desktop Settings should explain universal player keybinds.'
Assert-Match $desktopPlayerShortcuts "\['F', 'Enter or exit fullscreen'\]" 'Desktop player keybind guidance should retain universal fullscreen control.'
Assert-Match $desktopSettings 'Export desktop settings' 'Desktop Settings should expose safe settings export.'
Assert-Match $desktopSettings 'Import desktop settings' 'Desktop Settings should expose safe settings import.'
Assert-NotMatch $desktopSettings 'getSession\(\)|supabase\.auth|localStorage\.clear\(\)' 'Desktop Settings backup UI must not export session data or clear all storage.'
Assert-Match $desktopSchedule 'fetchCompleteSchedule' 'Desktop Schedule should load the complete live airing day rather than one partial page.'
Assert-Match $desktopSchedule 'Recent delay and cancellation alerts' 'Desktop Calendar should retain confirmed schedule alerts.'
Assert-Match $desktopNotificationCenter 'No delay or cancellation alerts' 'The notification center should be scoped to delay and cancellation updates.'
Assert-NotMatch $desktopNotificationCenter "kind === 'rescheduled'|Rescheduled" 'Reschedules should remain Calendar-only for now.'
Assert-Match $desktopScheduleRevisions "kind:\s*'delayed'\s*\|\s*'cancelled'" 'Schedule notification records should reject unrelated update kinds.'
Assert-Match $desktopShell 'DesktopNotificationCenter' 'The desktop notification bell should open the in-app notification center.'
Assert-Match $desktopShell 'topSearchInputRef' 'The desktop top search should be a real focusable input.'
Assert-Match $desktopShell 'navigate\(query \? `/search\?q=' 'Submitting the desktop top search should open matching Explore results.'
Assert-Match $desktopExplore 'fetchJikanExploreCatalog' 'Explore should hedge slow catalog refreshes through the native secondary path.'
Assert-Match $desktopExplore 'readDesktopExploreCatalog' 'Explore should restore its last verified result set immediately.'
Assert-Match $desktopExploreCache 'MAX_AGE_MS' 'Explore saved catalogs should have bounded retention.'
Assert-NotMatch $desktopExplore 'The primary catalog did not respond' 'Explore must not expose disruptive provider failure pages.'
Assert-Match $watchPage 'UpcomingNotifyButton' 'Upcoming anime pages should expose an airing notification action.'
Assert-Match $upcomingNotifyButton 'Notify me when this anime airs' 'Upcoming airing notifications should have an accessible action.'
Assert-Match $desktopReminders 'streamnyaa\.desktop\.upcomingWatches\.v1' 'Unknown upcoming dates should persist until their airing time is resolved.'
Assert-Match $desktopReminders 'reminderOffsetMinutes:\s*0' 'Upcoming anime notifications should fire when airing begins.'
Assert-Match $desktopReminders 'streamnyaa\.desktop\.scheduleReminders\.v1' 'Desktop Schedule should persist airing reminders with the expected storage key.'
Assert-Match $desktopSchedule 'getScheduleNotificationPermission' 'Desktop Schedule should use an explicit notification permission helper.'
Assert-Match $desktopReminders "delivery:\s*'system'" 'Desktop Schedule reminders should store native system delivery.'
Assert-Match $desktopSchedule 'Test notification' 'Desktop Schedule should expose a test notification action.'
Assert-Match $desktopSchedule 'Enable StreamNyaa in Windows notification settings' 'Desktop Schedule should explain how to unblock native notifications.'
Assert-Match $desktopSchedule 'Windows notifications enabled' 'Desktop Schedule should show native notification status.'
Assert-Match $desktopSchedule 'Native notifications unavailable' 'Desktop Schedule should report unsupported native notification delivery.'
Assert-Match $nyaaApi 'inMemorySearchCache' 'Desktop source fetch cache is missing.'
Assert-Match $nyaaApi 'Source search cancelled' 'Cancelled source searches must remain distinct from valid empty results.'
Assert-Match $metadataApi 'inFlightMetadataRequests' 'Desktop metadata requests should be coalesced to prevent provider rate-limit bursts.'
Assert-Match $metadataApi 'isValidDesktopMetadataPayload' 'Malformed primary metadata must be rejected before it reaches the persistent cache.'
Assert-Match $desktopCatalogCache 'if \(typeof window === .undefined. \|\| !key \|\| key\.length > 180 \|\| !Array\.isArray\(data\?\.data\) \|\| !data\.data\.length\) return' 'An ambiguous empty Home refresh must not overwrite last-known-good catalog data.'
Assert-Match $desktopSecurity 'redactDesktopDiagnostic' 'Desktop diagnostics must redact credentials and source links.'
Assert-Match $desktopQueryClient 'refetchOnReconnect:\s*true' 'Active desktop screens must refresh after connectivity returns.'
Assert-Match $metadataApi 'providerCooldowns' 'Desktop metadata layer should cool down providers after rate-limit/server errors.'
Assert-Match $metadataApi 'LOCAL_METADATA_MAX_STALE_MS' 'Desktop metadata layer should keep bounded stale fallback data.'
Assert-Match $metadataApi 'type MetadataProvider' 'Desktop metadata layer should use one provider type for all metadata integrations.'
Assert-Match $metadataApi 'fetchMetadataProviderPath' 'Desktop metadata layer should expose cached optional provider path requests.'
Assert-Match $metadataApi 'fetchAniDbAnimeMetadata' 'Desktop metadata layer should expose cached AniDB anime metadata requests.'
Assert-Match $streamSourcesApi 'inFlightMetadataCache' 'Metadata gateway should coalesce duplicate upstream calls.'
Assert-Match $streamSourcesApi 'STALE_TTL_MS' 'Metadata gateway should serve bounded stale data when providers fail.'
Assert-Match $streamSourcesApi 'fetchTmdb' 'Metadata gateway should support cached TMDB enrichment.'
Assert-Match $streamSourcesApi 'fetchAnimeSchedule' 'Metadata gateway should support cached AnimeSchedule enrichment.'
Assert-Match $streamSourcesApi 'fetchAniDb' 'Metadata gateway should support cached AniDB enrichment.'
Assert-Match $streamSourcesApi 'PROVIDER_DISABLED_TTL_SECONDS' 'Metadata gateway should fail closed for unconfigured optional providers.'
Assert-Match $desktopBridge "'anilist' \| 'jikan' \| 'anidb' \| 'animeschedule' \| 'tmdb'" 'Desktop metadata bridge type should include every supported metadata provider.'
Assert-Match $desktopBridge 'controlLocalPlayer' 'Desktop bridge should expose player control commands.'
Assert-Match $desktopBridge 'listenDesktopPlayerRecoveryRequest' 'Desktop bridge should expose stalled-player recovery requests.'
Assert-Match $watchPage 'runPlayerControl' 'Desktop watch page should wire the player control UI.'
Assert-Match $watchPage 'listenDesktopPlayerRecoveryRequest' 'Desktop watch page should handle same-episode backup recovery requests.'
Assert-Match $watchPage 'resumeOverride' 'Desktop backup recovery should preserve the current playback timestamp.'
Assert-Match $watchPage 'persistActivePlaybackCheckpoint' 'Desktop source switches and exits should flush the live playback checkpoint.'
Assert-NotMatch $watchPage 'progressPercent:\s*playbackProgress\.progress' 'Torrent download percentage must not be saved as watch progress.'
Assert-Match $watchPage 'buffer_percent' 'Desktop watch UI should render real playable-buffer telemetry.'
Assert-Match $watchPage 'Automatic recovery tried three backup releases' 'Midstream recovery must stop after a bounded number of backup releases.'
Assert-Match $watchPage "document\.visibilityState === 'hidden'\) return 8_000" 'Playback progress polling should slow down while the app is hidden.'
Assert-Match $watchPage 'Pause' 'Desktop watch page should expose a pause control.'
Assert-Match $tauriMain 'fn get_desktop_diagnostics' 'Desktop diagnostics command is missing.'
Assert-Match $tauriMain 'logs_root\(\)' 'Desktop log directory helper is missing.'
Assert-Match $tauriMain 'cleanup_abandoned_sessions' 'Desktop cache cleanup path is missing.'
Assert-Match $tauriMain 'fn rqbit_http_client' 'Local torrent telemetry and control requests should share a pooled HTTP client.'
Assert-Match $tauriMain 'update_only_files' 'Batch playback should prioritize only the selected episode and companion subtitles.'
Assert-Match $tauriMain 'source_cache_identity' 'Playback cache directories should be stable per torrent source.'
Assert-Match $tauriMain 'cleanup_transient_sessions' 'Startup should preserve healthy reusable source caches while removing abandoned transient sessions.'
Assert-Match $tauriMain 'play_local_torrent' 'Desktop local playback command is missing.'
Assert-Match $tauriMain 'PlayerControlRequest' 'Desktop player control request type is missing.'
Assert-Match $tauriMain 'control_local_player' 'Desktop player control command is missing.'
Assert-Match $tauriMain 'get_player_property_bool' 'Desktop player progress should expose boolean player state.'
Assert-Match $tauriMain 'torrent_progress_percent' 'Desktop telemetry should keep torrent completion separate from buffer completion.'
Assert-Match $tauriMain 'buffered_seconds' 'Desktop telemetry should expose playable seconds buffered ahead.'
Assert-Match $tauriMain 'buffer_advancing' 'Desktop telemetry should expose whether buffering is advancing.'
Assert-Match $tauriMain 'streamnyaa-player\.lua' 'Desktop player should load the StreamNyaa MPV control skin.'
Assert-Match $tauriMain 'streamnyaa-player-recovery-request' 'Rust should forward MPV recovery requests to the desktop watch page.'
Assert-Match $tauriMain 'STORAGE_GUARD_INTERVAL:\s*Duration\s*=\s*Duration::from_secs\(5\)' 'Runtime storage guards should avoid recursive directory scans every watchdog tick.'
Assert-Match $tauriMain 'Directory traversal can be expensive for large torrents' 'Storage guard scans should run outside the player-manager lock.'
Assert-Match $tauriMain '--osc=no' 'Desktop player should disable the default MPV OSC when the StreamNyaa skin is used.'
Assert-Match $playerSkin 'cycle_speed' 'StreamNyaa MPV skin should expose playback speed cycling.'
Assert-Match $playerSkin 'streamnyaa-mute' 'StreamNyaa MPV skin should expose mute controls.'
Assert-Match $playerSkin 'MBTN_LEFT_DBL' 'StreamNyaa MPV skin should support double-click fullscreen.'
Assert-Match $playerSkin 'bind_key\("f", "streamnyaa-fullscreen"' 'The universal F fullscreen shortcut is missing.'
Assert-Match $playerSkin 'bind_key\("k", "streamnyaa-k"' 'The universal K play/pause shortcut is missing.'
Assert-Match $playerSkin 'bind_key\("j", "streamnyaa-j"' 'The universal J rewind shortcut is missing.'
Assert-Match $playerSkin 'bind_key\("l", "streamnyaa-l"' 'The universal L forward shortcut is missing.'
Assert-Match $playerSkin 'bind_key\("N", "streamnyaa-next-episode"' 'The universal Shift+N next-episode shortcut is missing.'
Assert-Match $playerSkin 'keyboard_seek_percent' 'Number and Home/End seek shortcuts should share bounded percentage seeking.'
Assert-Match $playerSkin '(?s)function close_menu_or_overlay\(\).*?elseif state\.fullscreen then.*?safe_set_property\("fullscreen", "no"\)' 'Escape should exit native fullscreen after closing player menus.'
Assert-NotMatch $playerSkin '(?s)mp\.register_event\("end-file".{0,500}escape-fullscreen' 'End-of-file handling must not be coupled to the Escape fullscreen action.'
Assert-Match $playerSkin 'skip_only_rendered' 'Skip prompts must render independently from the full player timeline.'
Assert-Match $playerSkin 'newly_shown and now - \(ui\.last_direct_interaction or 0\) > 0\.9' 'Automatic skip prompts must not wake the complete control overlay.'
Assert-Match $playerSkin 'seek_hot' 'StreamNyaa MPV skin should expose seek preview hover state.'
Assert-Match $playerSkin 'BUFFER_TARGET_SECONDS\s*=\s*18' 'Buffer percentage fallback should use the configured 18-second playback target.'
Assert-Match $playerSkin 'BUFFER_STRESSED_TARGET_SECONDS\s*=\s*30' 'Repeated stalls should expand the native buffer target without affecting healthy streams.'
Assert-Match $playerSkin 'request_software_decoder_recovery' 'Healthy-buffer freezes should retry software decoding before discarding a working torrent.'
Assert-Match $playerSkin 'function apply_osd' 'Native player rendering should avoid submitting identical ASS frames.'
Assert-Match $playerSkin 'function check_playback_stall' 'StreamNyaa MPV skin should detect undeclared playback stalls.'
Assert-Match $playerSkin 'streamnyaa-player-recovery-request' 'StreamNyaa MPV skin should offer same-episode backup recovery.'
Assert-Match $playerSkin 'STALL_RECOVERY_SECONDS\s*=\s*12' 'Native buffering should attempt same-source recovery after a bounded no-progress interval.'
Assert-Match $playerSkin 'STALL_ACTION_SECONDS\s*=\s*10' 'A failed same-source recovery should move to a backup source promptly.'
Assert-Match $playerSkin 'STARTUP_STREAM_RETRY_SECONDS\s*=\s*12' 'A stream that never exposes a playable timeline must have a bounded startup retry.'
Assert-Match $playerSkin 'function check_startup_stream_stall' 'Pre-playback decoder stalls must be covered by their own watchdog.'
Assert-Match $playerSkin 'state\.has_started_playback and has_playable_media\(\)' 'Startup recovery must stay armed until MPV confirms real playback.'
Assert-Match $playerSkin '(?s)mp\.register_event\("playback-restart".*?state\.has_started_playback = true' 'MPV playback-restart must be the authoritative first-frame signal.'
Assert-Match $playerSkin 'FIRST_VIDEO_FRAME_GRACE_SECONDS\s*=\s*0\.35' 'The loading artwork must remain visible through the first decoded-frame handoff.'
Assert-Match $playerSkin 'function begin_first_video_frame_handoff' 'The player must perform an explicit artwork-to-video handoff.'
Assert-NotMatch $playerSkin '(?s)mp\.register_script_message\("streamnyaa-playback-ready".*?state\.has_started_playback = true' 'MPV shell readiness must never be mistaken for decoded video readiness.'
Assert-NotMatch $playerSkin 'function stall_watchdog_allowed\(\)\r?\n\s*if [^\r\n]*state\.core_idle' 'MPV core-idle cache waits must not disable stall recovery.'
Assert-Match $playerSkin 'Startup stream retry did not become playable; requesting backup' 'Failed startup reloads must request a verified backup source.'
Assert-Match $playerSkin 'safe_commandv\("loadfile", path, "replace", "-1"' 'Same-source recovery should reopen the HTTP stream using the current MPV command signature.'
Assert-Match $playerSkin 'state\.paused and not state\.paused_for_cache' 'Only deliberate pauses may suspend native stall recovery.'
Assert-Match $playerSkin 'state\.seeking' 'Intentional seeks must suspend native stall recovery.'
Assert-Match $playerSkin 'native_buffering_active\(\) then return 0' 'Buffering without measurable playable depth should show a truthful zero percent.'
Assert-Match $playerSkin 'restore_same_source_preferences' 'Same-source recovery should preserve player preferences and selected tracks.'
Assert-Match $playerSkin 'request_backup_source_recovery\(\)' 'A stalled native buffer should automatically request a verified backup source.'
Assert-NotMatch $playerSkin 'ui\.dragging or is_placeholder_media\(\) or native_buffering_active\(\)' 'Native cache pauses must remain inside the stall watchdog.'
Assert-Match $playerSkin 'function position_inside_skip_range' 'StreamNyaa MPV skin should gate skip actions to the active OP/ED range.'
Assert-Match $playerSkin '(?s)function manual_strict_skip_range\(kind, pos\).*skip_range_for_position\(kind, pos, false\)' 'Manual skip buttons must not use nearby/pre-roll skip windows.'
Assert-Match $playerSkin 'if not position_inside_skip_range\(range, pos\) then return false end' 'Auto skip should only run while the playhead is inside the skip range.'
Assert-Match $playerSkin 'range\.kind == "outro" and range\.source ~= "chapter"' 'Auto Skip Outro should only trust explicit ending/outro chapter markers.'
Assert-Match $tauriMain 'loading_frame' 'Desktop player should use a branded supported loading frame.'
Assert-Match $tauriMain 'image-display-duration=inf' 'Desktop player should hold the branded loading frame while buffering.'
Assert-Match $tauriMain 'PLAYER_COVER_PRELOAD_TIMEOUT_MS' 'Desktop player cover preparation should stay bounded before MPV opens.'
Assert-Match $tauriMain 'loading-cover\.jpg' 'Desktop player should prepare a cover-based loading image for MPV.'
Assert-Match $playerSkin 'string\.format\("%d%%", percent\)' 'Native startup loading must render a prominent numeric percentage.'
Assert-Match $playerSkin 'string\.format\("%.1f of %ds ready"' 'Native buffering must show playable seconds against its adaptive target.'
Assert-Match $tauriMain 'Center-crop with Lanczos' 'Landscape player art must fill the frame without blurred letterbox bands.'
Assert-Match $playerSkin 'function is_cover_loading_media' 'StreamNyaa MPV skin should recognize cover loading images as loading media.'
Assert-Match $playerSkin 'loading%-cover%.jpg' 'StreamNyaa MPV skin should not treat loading-cover.jpg as normal playable media.'
Assert-Match $watchPage 'function playerLandscapeCandidates' 'Desktop watch playback should collect genuine landscape artwork candidates.'
Assert-Match $watchPage 'bannerCandidates,' 'Desktop watch playback payload should send validated landscape artwork candidates to the native player.'
Assert-NotMatch $watchPage 'anime\?\.background' 'Free-form anime background text must never be interpreted as an artwork URL.'
Assert-Match $watchPage 'coverImage\?\.extraLarge' 'Desktop watch poster candidates should include AniList cover art for player loading fallback.'
Assert-Match $watchPage 'function youtubeVideoIdFor' 'Desktop trailers should validate and canonicalize YouTube URLs before opening them.'
Assert-Match $watchPage "url\.protocol !== 'https:'" 'Desktop trailer links must require HTTPS.'
Assert-Match $tauriMain 'validated_command_candidate' 'Desktop command overrides must pass the executable-name allowlist before launch.'
Assert-Match $tauriMain 'validated_desktop_source_api_url' 'The native source relay must validate the exact HTTPS origin and path.'
Assert-Match $tauriMain 'MAX_REMOTE_RESPONSE_BYTES' 'Remote metadata and source responses must have a bounded size.'
Assert-Match $tauriMain 'valid_desktop_metadata_payload' 'The native metadata cache must reject invalid primary responses.'
Assert-Match $tauriMain 'allowed_command\(value, allowed_names\)' 'Desktop command validation must reject arbitrary executable names.'
Assert-NotMatch $tauriConfig 'ws://localhost' 'Packaged desktop CSP must not permit unused WebSocket connections.'
Assert-Match $desktopHistory 'role="alertdialog"' 'Desktop History must confirm destructive cleanup inside the app.'
Assert-Match $desktopHistory "setPendingClear\('all'\)" 'Desktop History Clear all must arm confirmation instead of deleting immediately.'
Assert-Match $desktopBridge 'LOCAL_PLAYBACK_HISTORY_LIMIT\s*=\s*18' 'Desktop playback history must remain bounded.'
Assert-Match $desktopHome 'Resume' 'Continue Watching should expose Resume instead of Restart.'
Assert-NotMatch $desktopHome '>\s*Restart\s*<' 'Continue Watching must not offer a misleading restart action.'
Assert-Match $desktopHome '/nyaa\?\$\{detailsQuery\.toString\(\)\}' 'Continue Watching details should open the contextual Source Browser.'
Assert-Match $desktopSources "searchParams\.get\('animeId'\)" 'Source Browser should preserve canonical anime identity from Continue Watching.'
Assert-Match $desktopSources "searchParams\.get\('ep'\)" 'Source Browser should preserve the requested episode context.'
Assert-Match $desktopExplore 'contentVisibility' 'Desktop Explore should skip layout and paint work for off-screen cards.'
Assert-Match $desktopExplore 'desktop-explore-v2' 'Desktop Explore should cache each primary catalog selection independently.'
Assert-NotMatch $desktopExplore 'fallbackByMode|fallbackAnime\(' 'Desktop Explore must not inject fabricated fallback catalog entries.'
Assert-Match $desktopReminders 'DESKTOP_REMINDER_POLL_MS\s*=\s*45_000' 'Desktop reminder polling must remain bounded and non-aggressive.'
Assert-Match $desktopReminders 'sendNotification\(' 'Desktop reminders must use native Tauri notifications.'
Assert-Match $desktopShell 'deliverDueDesktopReminders' 'Desktop reminders must remain active outside the Calendar route.'
Assert-NotMatch $desktopSchedule 'new Notification\(' 'Calendar reminders must not fall back to the browser notification API.'
Assert-NotMatch $desktopSchedule 'Save in-app reminder' 'Calendar bells must not silently downgrade to in-app reminders.'
Assert-Match $tauriMain 'tauri_plugin_notification::init\(\)' 'The desktop runtime must initialize the native notification plugin.'
Assert-Match $tauriMain 'tauri_plugin_opener::init\(\)' 'Google OAuth must open in the system browser instead of an embedded WebView.'
Assert-Match $tauriMain 'tauri_plugin_deep_link::init\(\)' 'Desktop OAuth must initialize deep-link callbacks.'
Assert-Match $tauriMain 'tauri_plugin_single_instance::init' 'Desktop deep links must return to the already-running app instance.'
Assert-NotMatch $tauriMain 'WebviewWindowBuilder::new\(' 'Google OAuth must not use an embedded browser window.'
Assert-Match $tauriConfig '"schemes"\s*:\s*\["streamnyaa"\]' 'The desktop bundle must register the StreamNyaa auth scheme.'
Assert-NotMatch $tauriMain '(?s)WindowEvent::Resized\(_\).*?is_minimized' 'Normal window minimize/resize events must not unexpectedly send the app to tray.'
Assert-Match $tauriCapability 'notification:default' 'The main desktop window must be granted native notification permission.'
Assert-Match $desktopShell 'listenDesktopPlayerSettingChanged' 'Player preferences must be persisted by the always-mounted desktop shell.'
Assert-Match $tauriMain 'spawn_next_episode_request_watcher' 'Next-episode requests need a non-blocking file bridge in addition to MPV client messages.'
Assert-Match $playerSkin 'next_episode_request_file' 'The MPV skin must write reliable next-episode requests to the desktop bridge.'
Assert-Match $tauriMain 'spawn_player_setting_request_watcher' 'Player settings need a non-blocking persistence bridge in addition to MPV client messages.'
Assert-Match $playerSkin 'settings_request_file' 'The MPV skin must persist setting changes through the desktop bridge.'
Assert-Match $playerSkin 'return explicit_skip_range' 'Skip buttons and automatic skips must require explicit OP/ED chapter markers.'
Assert-NotMatch $playerSkin 'settings:theater' 'Theater Mode must not remain in the MPV settings menu.'
Assert-NotMatch $playerSkin 'button\(ass, mouse, "theater"' 'Theater Mode must not remain in the MPV control bar.'
Assert-Match $playerSkin 'add_region\("center_toggle"' 'The middle of the MPV viewport must be a play/pause target.'
Assert-Match $playerSkin 'id == "center_toggle"' 'The MPV center target must toggle pause through the existing control path.'
Assert-Match $playerSkin '(?s)function draw_center_play.*?icon_pause\(' 'The center player action must visibly represent both play and pause states.'
Assert-Match $desktopCss '--sn-accent:\s*#a50f28' 'Desktop pages must use the shared blood-red accent token.'
Assert-Match $desktopCss '(?s)\.desktop-app-shell \.sn-hero-panel.*?contain:\s*paint' 'Desktop media surfaces must isolate WebView paint composition.'
Assert-Match $desktopCss '(?s)\.desktop-app-shell \.sn-poster-card.*?backdrop-filter:\s*none' 'Desktop poster cards must not use the corrupt WebView backdrop path.'
Assert-Match $desktopCss '(?s)\.desktop-app-shell \.sn-explore-poster.*?transform:\s*none' 'Explore poster cards must avoid the WebView transform path that creates clipped cover wedges.'
Assert-Match $desktopCss '(?s)\.desktop-app-shell \.sn-poster-card img,.*?transform:\s*none\s*!important' 'All desktop poster images must avoid the WebView transform path that creates clipped cover wedges.'
Assert-Match $desktopExplore 'createPortal' 'Explore select menus should escape clipped filter and hero containers.'
Assert-Match $desktopExplore 'desktopPosterCandidates' 'Explore cards should use the shared portrait-safe artwork resolver.'
Assert-NotMatch $desktopArtwork 'anilist_id\s*\|\|\s*anime\?\.id\s*\|\|' 'Generic catalog ids must not be treated as AniList artwork ids.'
Assert-NotMatch $desktopHome '\[mask-image:' 'Desktop hero art must not use the WebView mask compositor.'
Assert-NotMatch $desktopExplore 'opacity-55 blur-2xl' 'Explore spotlight artwork must not overlay a blurred duplicate cover.'
Assert-Match $tauriMain '"tmdb"' 'Desktop metadata bridge should support TMDB enrichment requests.'
Assert-Match $tauriMain '"animeschedule"' 'Desktop metadata bridge should support AnimeSchedule enrichment requests.'
Assert-Match $tauriMain '"anidb"' 'Desktop metadata bridge should support AniDB enrichment requests.'
Assert-Match $tauriMain 'disabled_provider_value' 'Desktop metadata bridge should safely disable unconfigured optional providers.'
Assert-Match $packageJson 'preflight:desktop' 'Desktop tooling preflight script is missing.'
Assert-Match $packageJson 'verify:desktop-release' 'Desktop release verification script is missing.'
Assert-Match $packageJson 'test:frontend' 'Desktop verification must include executable frontend behavior tests.'
Assert-Match $packageJson 'serve-desktop-dist\.mjs' 'Desktop dev should serve the direct desktop bundle instead of the broken Vite shell.'
Assert-Match $packageJson 'build-desktop-fallback\.ps1' 'Desktop build should use the direct Windows-safe frontend builder.'
Assert-Match $desktopHtmlWriter 'inlineStyles' 'Desktop packaged HTML should inline CSS to avoid unstyled installed builds.'
Assert-Match $desktopHtmlWriter 'src="/assets/\$\{entry\.name\}"' 'Desktop packaged HTML should load the JS bundle from an absolute assets path.'
Assert-Match $desktopHtmlWriter 'streamnyaa-desktop-boot' 'Desktop packaged HTML should render the launch screen before React starts.'
Assert-Match $desktopHtmlWriter 'prefers-reduced-motion' 'Desktop launch motion must respect reduced-motion preferences.'
Assert-Match $mainDesktop 'updateDesktopBoot' 'Desktop entry should report a real pre-React startup milestone.'
Assert-Match $appDesktop 'completeDesktopBoot' 'Desktop launch screen should dismiss only after session restoration finishes.'
Assert-Match $desktopHtmlWriter 'aria-valuenow="8"' 'Desktop launch screen should expose a numeric initial progress value.'
Assert-Match $desktopHtmlWriter 'clamp\(88px,10vmin,154px\)' 'Desktop launch branding should scale with the active display resolution.'
Assert-Match $tauriMain 'artwork_layout' 'Desktop player metadata should identify the landscape loading-art layout.'
Assert-Match $tauriMain 'is_quality_landscape_art' 'Desktop player must validate landscape dimensions before accepting loading artwork.'
Assert-Match $tauriMain 'compose_full_landscape_art' 'Landscape player artwork should fill the viewport with high-quality resampling.'
Assert-Match $tauriMain 'portrait_player_art_is_rejected_instead_of_stretched_or_blurred' 'Portrait art must never become a stretched or blurred player background.'
Assert-Match $tauriMain 'player_art_candidates_never_use_the_portrait_poster' 'Portrait posters must stay outside the player landscape-art pipeline.'
Assert-Match $playerSkin 'ENABLE_COVER_BITMAP_OVERLAY\s*=\s*true' 'Prepared landscape artwork must remain composited during the first-frame transition.'
Assert-NotMatch $playerSkin '"150006"' 'Player loading fallback must not use the old purple fill.'
Assert-NotMatch $playerSkin 'rect\(ass, 0, height \* 0\.36' 'Player startup artwork must not use visible stacked overlay bands.'
Assert-NotMatch $playerSkin 'rect\(ass, 0, 0, width, height, C\.accent, 248\)' 'Player loading art must not receive the old full-screen red tint.'
Assert-Match $playerSkin 'startup_loading_percent' 'Player startup should render native playable-buffer progress.'
Assert-Match $playerSkin 'string\.format\("Reconnecting  ·  %d%%"' 'Player stall state should keep the live buffer percentage visible.'
Assert-Match $playerSkin 'string\.format\("%.1f of %ds ready"' 'Player buffering overlay should show real-time playable seconds against its target.'
Assert-Match $playerSkin 'bar_x1 \+ \(bar_x2 - bar_x1\) \* clamp\(percent / 100' 'Player buffering overlay should render a determinate compact progress bar.'
Assert-Match $playerSkin 'local base_offset = ui\.visible and 174 or 84' 'Manual intro and outro actions should remain raised above the player edge and controls.'
Assert-Match $playerSkin 'height - panel_h - 116 \* s' 'The next-episode panel should remain raised above the player edge.'
Assert-Match $desktopScheduleCache 'Array\.isArray\(data\?\.data\)' 'Schedule caching must preserve verified empty days instead of confusing them with request failures.'
Assert-Match $desktopSchedule 'scheduleQuery\.isError && !scheduleQuery\.data' 'Schedule request failures must remain distinct from verified empty days.'
Assert-Match $playerSkin 'OPENING THE VIDEO DECODER' 'Player loading copy should follow the real native startup stage.'
Assert-Match $desktopFallbackBuilder '--public-path=/assets' 'Desktop fallback assets should resolve from /assets on every route depth.'
Assert-Match $desktopFallbackBuilder "'--minify'" 'Desktop production JavaScript should be minified.'
Assert-Match $desktopFallbackBuilder "'--tree-shaking=true'" 'Desktop production JavaScript should tree-shake unused code.'
Assert-Match $tauriMain '\.clamp\(1, 3\)' 'Desktop direct source fallback should allow a wider page search window.'
Assert-Match $workflow 'STREAMNYAA_REQUIRE_BUNDLED_BINARIES' 'Release workflow must require bundled binaries.'

Write-Host 'Desktop verification passed.'
