import { MD3DarkTheme, MD3LightTheme, type MD3Theme } from 'react-native-paper';

export const tokens = {
  color: {
    brand: '#C11235',
    brandBright: '#E11D48',
    brandDeep: '#78091F',
    brandSoft: '#310A14',
    background: '#030304',
    backgroundRaised: '#070708',
    surface: '#0C0C0E',
    surfaceRaised: '#151518',
    surfacePressed: '#1C171A',
    glass: 'rgba(12, 12, 14, 0.82)',
    glassStrong: 'rgba(7, 7, 9, 0.94)',
    outline: '#292529',
    outlineSoft: 'rgba(255, 255, 255, 0.075)',
    outlineBrand: 'rgba(193, 18, 53, 0.42)',
    text: '#F6F3F4',
    textMuted: '#A9A2A6',
    textFaint: '#777176',
    success: '#62C995',
    warning: '#E8B44F',
    danger: '#FF6B82',
    scrim: 'rgba(2, 2, 3, 0.78)',
  },
  spacing: { xs: 4, sm: 8, md: 12, lg: 18, xl: 24, xxl: 36 },
  radius: { control: 8, card: 12, pill: 999 },
} as const;

export const darkTheme: MD3Theme = {
  ...MD3DarkTheme,
  roundness: 3,
  colors: {
    ...MD3DarkTheme.colors,
    primary: tokens.color.brandBright,
    onPrimary: '#FFFFFF',
    primaryContainer: tokens.color.brandSoft,
    onPrimaryContainer: '#FFD9E0',
    secondary: '#D9C2C8',
    onSecondary: '#2B151B',
    secondaryContainer: '#281C20',
    onSecondaryContainer: '#F0DDE2',
    background: tokens.color.background,
    onBackground: tokens.color.text,
    surface: tokens.color.surface,
    onSurface: tokens.color.text,
    surfaceVariant: tokens.color.surfaceRaised,
    onSurfaceVariant: tokens.color.textMuted,
    outline: tokens.color.outline,
    outlineVariant: tokens.color.outlineSoft,
    error: tokens.color.danger,
    elevation: {
      level0: 'transparent',
      level1: '#0C0B0D',
      level2: '#111012',
      level3: '#161315',
      level4: '#191517',
      level5: '#1D171A',
    },
  },
};

export const lightTheme: MD3Theme = {
  ...MD3LightTheme,
  roundness: 3,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#A50F2D',
    onPrimary: '#FFFFFF',
    primaryContainer: '#FFD9E0',
    onPrimaryContainer: '#3F0010',
    background: '#FCF8F9',
    onBackground: '#201A1C',
    surface: '#FFFBFC',
    onSurface: '#201A1C',
    surfaceVariant: '#F2EDEF',
    onSurfaceVariant: '#655C60',
    outline: '#827579',
    outlineVariant: '#D4C8CC',
    error: '#BA1A1A',
  },
};
